# Konfiguracja dla srodowiska lokalnego (uruchamianie z IDE)

# Sciezka do zapisu zdjec samochodow
file.upload-dir.cars=./uploads/car_photos

# Sciezka do zapisu ikon marek
file.upload-dir.icons=./uploads/icons
